esphome:
  name: warmte-meter-mbus
  friendly_name: warmte-meter-mbus

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:
  baud_rate: 0
  level: INFO 
  logs:
    sensor: INFO
    warmtemetermbus.sensor: INFO

# Enable Home Assistant API
api:
  encryption:
    key: "PsKaCvrdD8AjEdWsv7b32V2KGBf7kicJAqhE+/zU1H8="

ota:
  password: "e5264b2500ef5b812b82d4342c5a60f6"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Warmte-Meter-Mbus"
    password: "MHcfSqvZc6fe"

uart:
  baud_rate: 2400
  # WROOM Breadboard / PCB: TX 17, RX 16
  # tx_pin: 17
  # rx_pin: 16
  # WROVER PCB: TX 19, RX 18
  tx_pin: 19
  rx_pin: 18
  data_bits: 8
  parity: EVEN
  stop_bits: 1

sensor:
  - platform: HeatMeterMbus
    heat_energy_e1:
      name: heat_energy_e1
    volume_v1:
      name: volume_v1
    energy_e8_inlet:
      name: energy_e8_inlet
    energy_e9_outlet:
      name: energy_e9_outlet
    operating_hours:
      name: operating_hours
    error_hour_counter:
      name: error_hour_counter
    t1_actual:
      name: t1_actual
    t2_actual:
      name: t2_actual
    t1_minus_t2:
      name: t1_minus_t2
    power_e1_over_e3:
      name: power_e1_over_e3
    power_max_month:
      name: power_max_month
    flow_v1_actual:
      name: flow_v1_actual
    flow_v1_max_month:
      name: flow_v1_max_month
    info_no_voltage_supply:
      name: info_no_voltage_supply
    info_t1_above_range_or_disconnected:
      name: info_t1_above_range_or_disconnected
    info_t2_above_range_or_disconnected:
      name: info_t2_above_range_or_disconnected
    info_t1_below_range_or_shorted:
      name: info_t1_below_range_or_shorted
    info_t2_below_range_or_shorted:
      name: info_t2_below_range_or_shorted
    info_invalid_temp_difference:
      name: info_invalid_temp_difference
    info_v1_air:
      name: info_v1_air
    info_v1_wrong_flow_direction:
      name: info_v1_wrong_flow_direction
    info_v1_greater_than_qs_more_than_hour:
      name: info_v1_greater_than_qs_more_than_hour
    heat_energy_e1_old:
      name: heat_energy_e1_old
    volume_v1_old:
      name: volume_v1_old
    energy_e8_inlet_old:
      name: energy_e8_inlet_old
    energy_e9_outlet_old:
      name: energy_e9_outlet_old
    power_max_year_old:
      name: power_max_year_old
    flow_v1_max_year_old:
      name: flow_v1_max_year_old
    log_year:
      name: log_year
      id: log_year
    log_month:
      name: log_month
      id: log_month
    log_day:
      name: log_day
      id: log_day
    bus_voltage:
      name: bus_voltage

text_sensor:
  - platform: template
    id: log_date
    name: log_date
    lambda: |-
      if (!id(log_day).has_state() || !id(log_month).has_state() || !id(log_year).has_state()) {
        std::string notAvailableString("date not available");
        return notAvailableString;
      } else {
        char stringBuffer[11];
        for (int i = 0; i < 11; ++i) {
          stringBuffer[i] = '\0';
        }
        sprintf(
          stringBuffer, 
          "%.0f-%.0f-20%.0f", 
          round(id(log_day).state), 
          round(id(log_month).state), 
          round(id(log_year).state)
        );
        std::string dateString(stringBuffer);
        return dateString;
      }
